In [2]:
import numpy as np
import time
import 

In [28]:
x = np.zeros((0, 10000), dtype='float64')

In [33]:
old_time = time.time()
for i in range(100):
    y = np.ones((1, 10000))
#     x[i] = np.concatenate((x, y))
    np.concatenate((x,y))
df = time.time() - old_time
print(df)

0.043560028076171875


In [30]:
x.a

(100, 10000)

In [37]:
import torch

#### 维度最后一个代表一行的个数，也就是列数，然后倒数第二个代码行数，第一个代表行列的数目

In [46]:
x = torch.arange(24).reshape(2, 3, 4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [47]:
y = torch.arange(6).reshape(2,3)
y

tensor([[0, 1, 2],
        [3, 4, 5]])

In [48]:
y.T

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [69]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [70]:
id(A)

140584313068016

#### 浅拷贝，为源位置的引用，深拷贝clone为新的地址

In [66]:
B = A.clone() # 分配新内存
print(id(B))
B = A
print(id(B))

140584313066256
140584313782816


In [67]:
B[2, 3] = 100
A[2, 3]

tensor(100.)

#### 两个矩阵按照元素的乘法称为 哈达玛积（Hadamard product），数学符号圆圈有个·

In [71]:
A*B

tensor([[0.0000e+00, 1.0000e+00, 4.0000e+00, 9.0000e+00],
        [1.6000e+01, 2.5000e+01, 3.6000e+01, 4.9000e+01],
        [6.4000e+01, 8.1000e+01, 1.0000e+02, 1.1000e+03],
        [1.4400e+02, 1.6900e+02, 1.9600e+02, 2.2500e+02],
        [2.5600e+02, 2.8900e+02, 3.2400e+02, 3.6100e+02]])

#### sum求和永远是标量，除非指定axis来进行指定轴求和

In [72]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [92]:
A = torch.arange(20*2, dtype=torch.float32).reshape((2, 5, 4))
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

#### 指定维度求和，则结果的shape为去掉该轴的样子

In [75]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [77]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [81]:
A.sum(axis=[0, 1]) 

tensor([180, 190, 200, 210])

In [82]:
A.sum()

tensor(780)

In [94]:
A.mean(axis=0)

tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])

In [93]:
A.mean(), A.sum() / A.numel()

(tensor(19.5000), tensor(19.5000))

In [95]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

#### 保持总和或者均值时，维度（轴）数不变，尤其用在广播机制（广播的前提必须保证维度一致）

In [148]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

In [97]:
A / sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [149]:
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [102]:
z = torch.arange(6).reshape(2, 3)
z

tensor([[0, 1, 2],
        [3, 4, 5]])

In [112]:
z / torch.tensor([[0.2]])

tensor([[ 0.,  5., 10.],
        [15., 20., 25.]])

#### mean 只接受float和复数，无法对int取均值

In [136]:
b = torch.tensor([1,2,3], dtype=torch.float32)

In [137]:
b.dtype

torch.float32

In [138]:
torch.mean(b)

tensor(2.)

In [145]:
c = np.array([1,2,3], dtype='float32')

In [150]:
c.dtype

dtype('float32')

#### 计算A元素的累积总和

In [151]:
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [152]:
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [153]:
A.sum(axis=0)

tensor([[20., 22., 24., 26.],
        [28., 30., 32., 34.],
        [36., 38., 40., 42.],
        [44., 46., 48., 50.],
        [52., 54., 56., 58.]])

#### 向量的点积是相同位置元素乘积求和

In [154]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [155]:
torch.sum(x * y)

tensor(6.)

In [156]:
x * y

tensor([0., 1., 2., 3.])

#### 矩阵和向量、矩阵间的运算、范数

In [160]:
A.sum(axis=0).shape, x.shape, torch.mv(A.sum(axis=0), x)

(torch.Size([5, 4]), torch.Size([4]), tensor([148., 196., 244., 292., 340.]))

In [161]:
x

tensor([0., 1., 2., 3.])

In [162]:
A = A.sum(axis=0)

In [163]:
B = torch.ones(4, 3)

In [164]:
B.shape

torch.Size([4, 3])

In [165]:
A.shape

torch.Size([5, 4])

In [167]:
torch.mm(A, B)

tensor([[ 92.,  92.,  92.],
        [124., 124., 124.],
        [156., 156., 156.],
        [188., 188., 188.],
        [220., 220., 220.]])

In [170]:
# L2范数，元素^2 开根号
u = torch.tensor([3.0, -4.])
torch.norm(u)

tensor(5.)

In [172]:
# L1范数，绝对值求和
torch.abs(u).sum()

tensor(7.)

#### 矩阵Frobenius norm，矩阵元素的平方和的平方根，l2的拓展版

In [174]:
torch.norm(torch.ones((4,9,3)))

tensor(10.3923)

In [175]:
a = torch.ones((1,3))

In [178]:
b = a.clone()

In [179]:
id(a), id(b)

(140584312972768, 140584312974048)

#### torch中，行向量一维即可，列向量一般2维才能表示(n, 1)

#### 广播broadcasting
numpy原则上针对element级别，某些情况广播很高效 ，最简单的numpy 和 标量scalar乘积，比对应长度的array高效
A B从右往左维度数比较，逐元素查看，满足两个条件即可：两者其中维度1，或者相同

In [197]:
以下均可广播
Image  (3d array): 256 x 256 x 3
Scale  (1d array):         3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B     (3d array):     7 x 1 x 5
Result (4d array):   8 x 7 x 6 x 5

A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array): 5 x 4
B      (1d array):    4
Result (2d array):  5 x 4

A      (3d array):15 x 3 x 5
B      (3d array):15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):     3 x 5
Result (3d array):   15 x 3 x 5

A      (3d array):15 x 3 x 5
B      (2d array):    3 x 1
Result (3d array):  15 x 3 x 5

SyntaxError: invalid syntax (601557696.py, line 2)

In [195]:
A = torch.tensor([1, 2, 3])
# B = torch.tensor([2])
old_t = time.time()
for i in range(10000):
    A * 2
print(time.time() - old_t)

0.015851259231567383


In [200]:
a = torch.ones((10, 3))
b = torch.ones((1, 3))
a - b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])